### ISSUE TITLE
How to enable autocomplete while typing address in compose window

### ISSUE THREAD

**Issue by ghost** [t3chguy/Roundcube-SQL-Global-Address-Books#1]
Hi @t3chguy,

Latest development edition of your plugin works, but how to enable autocomplete while typing address in compose window?

**Comment by t3chguy** [comment]
![image](https://cloud.githubusercontent.com/assets/2403652/6021388/5d7bd2f6-abad-11e4-940f-766fc9e1c34d.jpg)
![image](https://cloud.githubusercontent.com/assets/2403652/6021389/5d7dd89e-abad-11e4-9487-e163f3ea9591.jpg)

If you look above you can see I don't have this issue, tested on Chrome, iOS Safari, Mac OSX Safari.
Or am I misunderstanding your issue?

**Comment by ghost** [comment]
I mean the behavior in image #1. It doesn't popup. Anything i can do to help debug this? Or any parameter i should set/change?

Tested on CentOS 7, PHP 5.4.16.

**Comment by t3chguy** [comment]
Could be the PHP Version but I doubt since to implement AutoComplete all I have to do is provide Roundcube with a method to access all Records through a complimentary Data Set. Which Book Type are you using?

**Comment by ghost** [comment]
SQL/iredmail.sql. I tried to test only users first.

**Comment by t3chguy** [comment]
Show me your config file? By default all books types are disabled
Autocomplete works for all ENABLED Books

**Comment by ghost** [comment]
``` php
<?php
$config['_sql_supportbook']     = array();
$config['_sql_domainbook']      = array('*');
$config['_sql_db_read_allowed'] = array('*');
$config['_sql_db_read_hidden']  = array('');
$config['_sql_globalbook']      = NULL;
$config['_sql_globalbook_gp']   = true;
$config['_sql_gb_read_allowed'] = array('*');
$config['_sql_gb_data_allowed'] = array('*');
$config['_sql_gb_read_hidden']  = array('');
$config['_sql_gb_data_hidden']  = array('');
```

**Comment by t3chguy** [comment]
You seem to want the DomainBook Enabled, it shouldn't be set to an ARRAY, instead just a string.
See Screenshot.
![image](https://cloud.githubusercontent.com/assets/2403652/6022181/0a70baf8-abb3-11e4-98a8-7f2d01364704.jpg)

**Comment by t3chguy** [comment]
I realise the configuration comment for this is wrong, sorry about that. Please let me know if it works once you change it to a String which should be the name you want the Address Book to have.

**Comment by ghost** [comment]
This setting doesn't work:

``` php
<?php
$config['_sql_supportbook']     = array();
$config['_sql_domainbook']      = 'Domain Book';
$config['_sql_db_read_allowed'] = array('*');
$config['_sql_db_read_hidden']  = array('');
$config['_sql_globalbook']      = NULL;
$config['_sql_globalbook_gp']   = true;
$config['_sql_gb_read_allowed'] = array('*');
$config['_sql_gb_data_allowed'] = array('*');
$config['_sql_gb_read_hidden']  = array('');
$config['_sql_gb_data_hidden']  = array('');
```

Well, i must point out that the comments and parameter names are all confuse. I'm lost ...

Here's my suggestion:
- Use variable names more straightforward. For example:

``` php
// Allow user to query/search/view all accounts under same domain: true, false.
$config['enable_per_domain_address_book'] = true;

// Allow user to query/search/view all accounts stored in SQL database: true, false.
$config['enable_global_address_book'] = true;
```

**Comment by t3chguy** [comment]
Yeah I'll change it when I get home tonight, except not True/False, it'll be Null/String containing name. Do you see an addressbook called 'Domain Book' under Address Books?

**Comment by ghost** [comment]
Yes, i can see 'Domain Book' under Address Books, and it works. Just cannot auto-complete while typing address in compose window.

**Comment by t3chguy** [comment]
I will get back to you when I get home, I haven't individually tested the DomainBook, even though they all use the same codebase.

**Comment by t3chguy** [comment]
DomainBook AutoComplete works for me fine, I will spin up a CentOS7 VPS to test further [same PHP Ver]

**Comment by t3chguy** [comment]
I can confirm that this issue happens to me on the same platform, I will look into it over the next 48 hours. Thanks for reporting it, I personally stick to Latest PHP so would have never discovered any issues otherwise.

**Comment by t3chguy** [comment]
@zhanghuangbin I have found the issue to only exist when a Support Book is not defined, AND running PHP < 5.5
[Broken replacement array_column function]
If there were no elements instead of returning an Empty Array, it'd return an Empty String. Will push a fix immediatelly, please let me know if it is working for you when you get a chance to test it!

**Comment by t3chguy** [comment]
Fix pushed, will begin refactor of config to slightly more readable format. Will push a new release once this is done!

**Comment by ghost** [comment]
It pops up candidates, but doesn't work correctly. For example, i have one domain `a.cn` and 2 users: `postmaster@a.cn`, `2nd@a.cn`, when i typing `2nd` in `To:` field, it pops up 3 candidates: `2nd@a.cn`, `postmaster@a.cn`, and `a.cn (1)`. But it should popup `2nd@a.cn` only (with SQL query `WHERE email LIKE '2nd%'`).

In Address Book view, it works fine.

I turned on log in MariaDB server to check what SQL commands it executes, and found this:

``` sql
1: SELECT * FROM global_addressbook WHERE domain='a.cn'
2: SELECT * FROM global_addressbook WHERE domain NOT IN ("", '')
3: SELECT domain FROM global_addressbook GROUP BY domain
```

Obviously, `WHERE xx NOT IN (... EMPTY LIST ...)` in second SQL command is not good (does it read `_sql_db_read_hidden`?).

Maybe it's better to check settings first, then generate a new WHERE statement to merge SQL command 1 and 2?

Also, do we need SQL command 3 above? What does `SELECT domain ...` used for?

**Comment by t3chguy** [comment]
1. Is the only query that should be running with only the DomainBook Enabled. Did you enable more books?

It does NOT read `_sql_**_read_hidden`
2. Should only ever get called for the 'Global Book' which has a `_sql_gb_data_hidden`
So for some reason Roundcube is querying my plugin for the AddressBook 'Global' as well as DomainBook. Did you enable this by chance? There is no way to merge queries for two completely separate Address Books as they won't share Object Instance.

The third one is really really strange, it is in the code for `list_groups`, which should only be executed for the Global Book. There's literally an IF Statement there saying if groups are disabled for that Book then don't run the query. [Again Roundcube is querying my plugin for a book with an id of global, did you enable this in config?]

Lastly, about the searching, that is for the lack of a custom search feature built into my plugin, it'll be remedied in the next update.

**Comment by ghost** [comment]
Here's my config. Maybe i should not complain, but i still cannot clearly understand comments and settings in `config.inc.php`. :(

``` php
<?php
$config['_sql_domainbook_name']  = 'Domain Address Book';
$config['_sql_db_read_allowed']  = array('*');
$config['_sql_db_read_hidden']   = array('');
$config['_sql_globalbook_name']  = NULL;
$config['_sql_globalbook_gp']    = true;
$config['_sql_gb_read_allowed']  = array('*');
$config['_sql_gb_data_allowed']  = array('*');
$config['_sql_gb_read_hidden']   = array('');
$config['_sql_gb_data_hidden']   = array('');
$config['_sql_supportbook_list'] = array();
```

**Comment by t3chguy** [comment]
Your Global Address Book is disabled, there is no reason for Roundcube to be querying my plugin, do you have any other Additional Address Books which may have the ID of 'global'?

**Comment by ghost** [comment]
No additional third-party plugins, just yours. :)
Enabled plugin in Roundcube:

``` php
$config['plugins'] = array('managesieve', 'password', 'wdgrc_sql_contacts');
```

**Comment by t3chguy** [comment]
Alright well once I get the search feature up and running, I'll use your config in my setup and see whether I have the same result on a Debugged MariaDB Server, if I do then I will look into why Roundcube is calling it, while it isn't perfect, it shouldn't cause any issues. I never mentioned, the 3rd statement is how the GlobalBook builds its array of Groups.

**Comment by t3chguy** [comment]
@zhanghuangbin If you clone the git, or download the pre-release you will have Decent [not fully tested] search functionality, which seems to work well in the Compose Mode. I have also streamlined the queries as much as I could without more testing, such as no more `NOT IN ('')` but there now may be large filtering blocks for the searching algorithm, which in the end probably makes the queries a little more expensive...
One thing about the configuration you may not understand is,

You could remove the following lines:

``` php
$config['_sql_db_read_allowed']  = array('*');
$config['_sql_db_read_hidden']   = array('');
$config['_sql_globalbook_name']  = NULL;
$config['_sql_globalbook_gp']    = true;
$config['_sql_gb_read_allowed']  = array('*');
$config['_sql_gb_data_allowed']  = array('*');
$config['_sql_gb_read_hidden']   = array('');
$config['_sql_gb_data_hidden']   = array('');
$config['_sql_supportbook_list'] = array();
```

Your configuration file is best looking like this:

``` php
<?php
$config['_sql_domainbook_name']  = 'Domain Address Book';
```

The Config has changed minorly, `*_hidden` should no longer be `array('')` and instead `NULL` or `array()` [or just not exist]

**Comment by ghost** [comment]
I will tested it soon.

Suggestion: how about this:

*) In default config file `config.inc.php.dist`, enable domain address book by default.
*) Disable AND comment out all other optional settings by default.

This way, admin enables per-domain address book without additional modification.

**Comment by ghost** [comment]
I'm afraid that it's worse now. I checked SQL commands it executes:

``` sql
SELECT * FROM global_addressbook WHERE (`email` <> '') AND domain='a.cn'
SELECT * FROM global_addressbook WHERE ((`email` <> '') AND `email` <> '' AND `email` <> '') AND domain='a.cn'
SELECT * FROM global_addressbook WHERE (((`email` <> '') AND `email` <> '' AND `email` <> '') AND `email` <> '' AND `email` <> '' AND `email` <> '') AND domain='a.cn'
SELECT * FROM global_addressbook WHERE ((((`email` <> '') AND `email` <> '' AND `email` <> '') AND `email` <> '' AND `email` <> '' AND `email` <> '') AND `email` <> '' AND `email` <> '' AND `email` <> '' AND `email` <> '') AND domain='a.cn'
SELECT * FROM global_addressbook WHERE ((((`email` <> '') AND `email` <> '' AND `email` <> '') AND `email` <> '' AND `email` <> '' AND `email` <> '') AND `email` <> '' AND `email` <> '' AND `email` <> '' AND `email` <> '') AND domain='a.cn'
```
1. Why so many `email <>''`? What does it used for? Why so many duplicate `email <> ''`? With iRedMail, if you create VIEW from `vmail.mailbox` table, `email` field of this view (column `mailbox.username`) will always has full email address.
2. Why more SQL queries than before?

**Comment by ghost** [comment]
In `To:` field of compose mode, if i type part of email address, it should query with the part i typed.
For example, i have `user@domain.com`, and i type `us` (first 2 letters of email address), it should query `WHERE email LIKE 'us%'` ('xx%' will use INDEX for querying, so no performance issue here).

**Comment by t3chguy** [comment]
The Search part of the Roundcube Contacts is awful, it is a multistage approach, basically I have to build the filter in one method and then Roundcube takes it, plays about with it and if it conforms then it gives it back to my Class to use for the actual MySQL Query, I'll take a look into how I can conform with this without it having such duplicates.

Okay, after some debugging of my own, RoundCube is receiving a Book IDd 'domain' but then asking for the content of the 'global' book, I have no idea why, or even how it managed to work with this peculiar manifest. I'll keep debugging

-EDIT-
Ohhh, I was adding Global to the Autocomplete Array even if it wasn't enabled, which is why the 3rd SQL Statement was getting executed in the first post.

**Comment by t3chguy** [comment]
Okay, in my Dev Platform I have it working much better now, it should be `One Query / Per Book / Per Change in TO Field`

**Comment by t3chguy** [comment]
@zhanghuangbin v2.4 is about to be released, hopefully the Searching is working for you, it has been a lot of work to get it working properly. Let me know if it works for you!

**Comment by ghost** [comment]
Wow, now it works. :)

I tried to type letters `a.cn` which is not prefix of an email address, it executed below SQL commands (only one SQL command, that's great. :)):

``` sql
SELECT * FROM global_addressbook WHERE (`name` LIKE '%a.cn%' OR `firstname` LIKE '%a.cn%' OR `surname` LIKE '%a.cn%' OR `email` LIKE '%a.cn%') AND domain='a.cn'
```

With iRedMail, as defined in your SQL/iredmail.sql, querying `name LIKE '%a.cn%'` includes all result returned by querying `firstname LIKE '%a.cn%' OR surname LIKE '%a.cn%'`, so maybe we can remove it here for better performance. Maybe it's necessary with other mail server solution.

**Comment by t3chguy** [comment]
While I may be able to do that, it will then no longer conform to RoundCube Autocomplete Standards, as Roundcube feeds me a list of columns it would like to search, so in some use-case-scenario it may just give me the column name, I might look into this as it'll help the query a tiny bit, but as far as I am aware this Issue is now fixed.
